name: CI/CD Pipeline Manual with threads
on:
  workflow_dispatch:
    inputs:
      threads:
        description: Threads to run on
        required: true
        type: choice
        default: "test:run:one"
        options:
          - "test:run:one"
          - "test:run:two"
          - "test:run:four"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run ${{ inputs.threads }}
        env:
          CYPRESS_LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          CYPRESS_INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
